### PR TITLE
Update name of claims

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

update the name of the claim with the entitlements.

### CODE REVIEW

**Comment by gwarf** [comment]
Should this be reviewed?

**Comment by enolfc** [comment]
yes, was willing to add @vardizzone-lab here, but got stuck in GitHub team membership

**Comment by gwarf** [comment]
OK, I invited her to join the org and some teams.

**Comment by enolfc** [comment]
@vardizzo-lab, can you re-do the review? and then don't close the PR, it needs to be merged first!

**Pull request merged**
